# Generated by Django 5.0.6 on 2024-06-10 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komentarz',
            old_name='data_utworzenia',
            new_name='data_publikacji',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_utworzenia',
            new_name='data_publikacji',
        ),
        migrations.AddField(
            model_name='customuser',
            name='imie',
            field=models.CharField(default='Nieznane', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nazwisko',
            field=models.CharField(default='Nieznane', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wiek',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='komentarz',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tytul',
            field=models.CharField(max_length=100),
        ),
    ]
